from __future__ import annotations
from utils import VALUE_TYPE_ENUM


def _param_entry(param: dict) -> str:
    """Format a single ParamMeta initializer."""
    name = param.get("name", "")
    type_str = param.get("type", "UINT8")
    required = "true" if param.get("required", True) else "false"
    desc = param.get("description", "")
    max_len = param.get("maxLength", 0) if type_str == "STRING" else 0
    default = param.get("default", "")
    return (
        f'            {{"{name}", {VALUE_TYPE_ENUM[type_str]}, {required}, '
        f'"{desc}", {max_len}, "{default}"}}'
    )


def generate(all_data: list[dict]) -> str:
    lines: list[str] = []

    lines.append("""\
//
// CommandRegistry.cpp
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#include "opx/pc/registry/CommandRegistry.h"
#include "autogen/shared/CommandTypes.h"
#include "opx/shared/core/Config.h"

#ifndef OPX_TARGET_EMBEDDED

void CommandRegistry::initialize() {
""")

    for data in all_data:
        device_name = data["device"]

        # Regular commands
        for cmd in data.get("commands", []):
            name = cmd["name"]
            desc = cmd.get("description", "")
            params = cmd.get("params", [])
            param_entries = ",\n".join(_param_entry(p) for p in params)
            param_block = f"{{\n{param_entries}\n        }}" if params else "{}"

            lines.append(f"    // {name}")
            lines.append(f"    registerCommand({{")
            lines.append(f"        {device_name}CommandType::{name},")
            lines.append(f'        "{name}",')
            lines.append(f'        "{desc}",')
            lines.append(f"        {param_block}")
            lines.append(f"    }});\n")

        # Auto-generated telemetry GET commands
        for src in data.get("telemetry", []):
            name = src["name"]
            desc = src.get("description", "")
            lines.append(f"    // GET_{name} (auto-generated telemetry request)")
            lines.append(f"    registerCommand({{")
            lines.append(f"        {device_name}CommandType::GET_{name},")
            lines.append(f'        "GET_{name}",')
            lines.append(f'        "Request current value of: {desc}",')
            lines.append(f"        {{}}")
            lines.append(f"    }});\n")

        # Auto-generated setting GET/SET commands
        for setting in data.get("settings", []):
            name = setting["name"]
            desc = setting.get("description", "")

            lines.append(f"    // GET_SETTING_{name} (auto-generated setting GET)")
            lines.append(f"    registerCommand({{")
            lines.append(f"        {device_name}CommandType::GET_SETTING_{name},")
            lines.append(f'        "GET_SETTING_{name}",')
            lines.append(f'        "Get current value of: {desc}",')
            lines.append(f"        {{}}")
            lines.append(f"    }});\n")

            lines.append(f"    // SET_SETTING_{name} (auto-generated setting SET)")
            lines.append(f"    registerCommand({{")
            lines.append(f"        {device_name}CommandType::SET_SETTING_{name},")
            lines.append(f'        "SET_SETTING_{name}",')
            lines.append(f'        "Set value of: {desc}",')
            lines.append(f"        {{}}")
            lines.append(f"    }});\n")

    lines.append("} // CommandRegistry::initialize()\n")
    lines.append("#endif // OPX_TARGET_EMBEDDED\n")

    return "\n".join(lines)
