from __future__ import annotations
from utils import build_command_id, to_hex
from utils import (
    CATEGORY_COMMAND,
    CATEGORY_TELEMETRY,
    CATEGORY_SETTING_GET,
    CATEGORY_SETTING_SET,
)


def generate(all_data: list[dict]) -> str:
    lines: list[str] = []

    lines.append("""\
//
// CommandTypes.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#pragma once

#include "opx/shared/core/platform.h"
""")

    for data in all_data:
        device_name = data["device"]
        type_shift = data["typeShift"]

        lines.append(f"// Device: {device_name}")
        lines.append(f"namespace {device_name}CommandType {{\n")

        # Regular commands
        for cmd in data.get("commands", []):
            name = cmd["name"]
            cmd_id = build_command_id(type_shift, CATEGORY_COMMAND, cmd["id"])
            if cmd.get("description"):
                lines.append(f"    // {cmd['description']}")
            lines.append(f"    constexpr uint16_t {name} = {to_hex(cmd_id)};\n")

        # Auto-generated telemetry GET commands
        if data.get("telemetry"):
            lines.append("    // --- Auto-generated telemetry request commands ---\n")
            for src in data["telemetry"]:
                name = src["name"]
                get_id = build_command_id(type_shift, CATEGORY_TELEMETRY, src["id"])
                if src.get("description"):
                    lines.append(
                        f"    // Request current value of: {src['description']}"
                    )
                lines.append(f"    constexpr uint16_t GET_{name} = {to_hex(get_id)};\n")

        # Auto-generated setting GET/SET commands
        if data.get("settings"):
            lines.append(
                "    // --- Auto-generated setting request and set commands ---\n"
            )
            for setting in data["settings"]:
                name = setting["name"]
                local_id = setting["id"]
                get_id = build_command_id(type_shift, CATEGORY_SETTING_GET, local_id)
                set_id = build_command_id(type_shift, CATEGORY_SETTING_SET, local_id)
                if setting.get("description"):
                    lines.append(
                        f"    // Get current value of: {setting['description']}"
                    )
                lines.append(
                    f"    constexpr uint16_t GET_SETTING_{name} = {to_hex(get_id)};\n"
                )
                if setting.get("description"):
                    lines.append(f"    // Set value of: {setting['description']}")
                lines.append(
                    f"    constexpr uint16_t SET_SETTING_{name} = {to_hex(set_id)};\n"
                )

        lines.append(f"}} // namespace {device_name}CommandType\n")

    return "\n".join(lines)
