from __future__ import annotations


def generate(all_data: list[dict]) -> str:
    lines: list[str] = []

    lines.append("""\
//
// DeviceManifest.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//
// Maps each device's typeShift to its display name and the list of
// command IDs it supports. Used by the PC side to build device/command
// menus at runtime without needing compile-time type knowledge.
//

#pragma once

#ifndef OPX_EMBEDDED

#include <cstdint>
#include <string>
#include <vector>
#include "autogen/shared/CommandTypes.h"

struct DeviceManifestEntry {
    uint8_t               typeShift;
    const char*           displayName;
    std::vector<uint16_t> commandIDs;
};

// Returns the full device manifest as a static local — generated once.
inline const std::vector<DeviceManifestEntry>& getDeviceManifest() {
    static const std::vector<DeviceManifestEntry> manifest = {
""")

    for i, data in enumerate(all_data):
        if "device" not in data or "typeShift" not in data:
            continue

        device_name = data["device"]
        type_shift = data["typeShift"]
        is_last = i == len(all_data) - 1

        lines.append(f"        // ── {device_name} (typeShift={type_shift})")
        lines.append("        {")
        lines.append(f"            {type_shift},")
        lines.append(f'            "{device_name}",')
        lines.append("            {")

        for cmd in data.get("commands", []):
            lines.append(f"                {device_name}CommandType::{cmd['name']},")

        if data.get("telemetry"):
            lines.append("                // auto-generated telemetry request commands")
            for src in data["telemetry"]:
                lines.append(
                    f"                {device_name}CommandType::GET_{src['name']},"
                )

        if data.get("settings"):
            lines.append("                // auto-generated setting GET/SET commands")
            for setting in data["settings"]:
                name = setting["name"]
                lines.append(
                    f"                {device_name}CommandType::GET_SETTING_{name},"
                )
                lines.append(
                    f"                {device_name}CommandType::SET_SETTING_{name},"
                )

        lines.append("            }")
        lines.append("        }" + ("" if is_last else ","))

    lines.append("""\
    };
    return manifest;
}

#endif // OPX_EMBEDDED
""")

    return "\n".join(lines)
