from __future__ import annotations
from utils import max_packed_param_size


def generate(all_data: list[dict]) -> str:
    max_size = max(max_packed_param_size(data) for data in all_data)

    return f"""\
//
// GeneratedConfig.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#pragma once

#include "opx/shared/core/platform.h"

// Maximum packed parameter bytes across all commands and settings in this project.
// Used to size PackedCommand::paramBytes in CommandQueue.
constexpr uint8_t MAX_PACKED_PARAM_SIZE = {max_size};
"""
