from __future__ import annotations


def generate(all_data: list[dict]) -> str:
    lines: list[str] = []

    lines.append("""\
//
// OpxDevices.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
// Contains device-specific includes derived from your device manifest files.
//

#pragma once
""")

    for data in all_data:
        device_name = data["device"]
        identity_only = data.get("identityOnly", False)
        target = data["target"]
        subdir = "pc" if target == "pc" else "embedded"

        lines.append(f"// {device_name}")
        lines.append(f'#include "devices/{device_name}/{device_name}Controller.h"')

        if not identity_only:
            lines.append(
                f'#include "../{subdir}/devices/{device_name}/{device_name}RegisterAll.h"'
            )
        lines.append(
            f'#include "../{subdir}/devices/{device_name}/{device_name}Register.h"'
        )
        lines.append("")

    return "\n".join(lines)
