from __future__ import annotations
from utils import trigger_config_expression, VALUE_TYPE_ENUM


def _build_bodies(data: dict, device_name: str, receiver: str) -> tuple[str, str]:
    settings = data.get("settings", [])
    telemetry = data.get("telemetry", [])

    if settings:
        settings_body = "\n".join(
            f"    {receiver}.registerSetting("
            f"SettingID::{device_name}Setting::{s['name']}, "
            f"{VALUE_TYPE_ENUM[s['type']]});"
            for s in settings
        )
    else:
        settings_body = f"    // No settings defined for {device_name}"

    if telemetry:
        telemetry_body = "\n".join(
            f"    {receiver}.registerTelemetry("
            f"TelemetrySource::{device_name}TelemetrySource::{src['name']}, "
            f"{trigger_config_expression(src)});"
            for src in telemetry
        )
    else:
        telemetry_body = f"    // No telemetry defined for {device_name}"

    return settings_body, telemetry_body


def _generate_embedded(data: dict, device_name: str) -> str:
    settings_body, telemetry_body = _build_bodies(data, device_name, "device")

    return f"""\
//
// {device_name}RegisterAll.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#pragma once
#include "opx/shared/core/Config.h"

#ifdef OPX_TARGET_EMBEDDED

#include "opx/shared/core/platform.h"
#include "opx/embedded/core/OpxDevice.h"
#include "opx/shared/core/TriggerConfig.h"
#include "autogen/shared/SettingIDs.h"
#include "autogen/shared/TelemetrySourceIDs.h"

inline void register{device_name}Settings(OpxDevice& device) {{
{settings_body}
}}

inline void register{device_name}Telemetry(OpxDevice& device) {{
{telemetry_body}
}}

#endif // OPX_TARGET_EMBEDDED
"""


def _generate_pc(data: dict, device_name: str) -> str:
    settings_body, telemetry_body = _build_bodies(data, device_name, "session")

    return f"""\
//
// {device_name}RegisterAll.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#pragma once
#include "opx/shared/core/Config.h"

#ifdef OPX_TARGET_PC

#include "opx/pc/core/OpxSession.h"
#include "opx/shared/core/TriggerConfig.h"
#include "autogen/shared/SettingIDs.h"
#include "autogen/shared/TelemetrySourceIDs.h"

inline void register{device_name}Settings(OpxSession& session) {{
{settings_body}
}}

inline void register{device_name}Telemetry(OpxSession& session) {{
{telemetry_body}
}}

#endif // OPX_TARGET_PC
"""


def generate(data: dict) -> str:
    device_name = data["device"]
    target = data["target"]

    if target == "pc":
        return _generate_pc(data, device_name)
    return _generate_embedded(data, device_name)
