from __future__ import annotations


def _generate_embedded(data: dict, device_name: str, identity_only: bool) -> str:
    if identity_only:
        body = f"    device.setTypeShift({device_name}Controller::TYPE_ID);\n"
        includes = ""
    else:
        body = (
            f"    device.setTypeShift({device_name}Controller::TYPE_ID);\n"
            f"    register{device_name}Settings(device);\n"
            f"    register{device_name}Telemetry(device);\n"
        )
        includes = f'#include "{device_name}RegisterAll.h"\n'

    return f"""\
//
// {device_name}Register.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#pragma once
#include "opx/shared/core/Config.h"

#ifdef OPX_TARGET_EMBEDDED

#include "opx/shared/core/platform.h"
#include "opx/embedded/core/OpxDevice.h"
#include "autogen/shared/devices/{device_name}/{device_name}Controller.h"

{includes}
// Single call to fully register this device with OpxDevice.
// Sets typeShift, registers all settings and telemetry sources.
inline void register{device_name}(OpxDevice& device) {{
{body}}}

#endif // OPX_TARGET_EMBEDDED
"""


def _generate_pc(data: dict, device_name: str, identity_only: bool) -> str:
    if identity_only:
        body = f"    session.setTypeShift({device_name}Controller::TYPE_ID);\n"
        includes = ""
    else:
        body = (
            f"    session.setTypeShift({device_name}Controller::TYPE_ID);\n"
            f"    register{device_name}Settings(session);\n"
            f"    register{device_name}Telemetry(session);\n"
        )
        includes = f'#include "{device_name}RegisterAll.h"\n'

    return f"""\
//
// {device_name}Register.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#pragma once
#include "opx/shared/core/Config.h"

#ifdef OPX_TARGET_PC

#include "opx/pc/core/OpxSession.h"
#include "autogen/shared/devices/{device_name}/{device_name}Controller.h"
{includes}
// Single call to fully register this device (as this identity) with OpxSession.
// Sets typeShift, registers all settings and telemetry sources.
inline void register{device_name}(OpxSession& session) {{
{body}}}

#endif // OPX_TARGET_PC
"""


def generate(data: dict) -> str:
    device_name = data["device"]
    identity_only = data.get("identityOnly", False)
    target = data["target"]

    if target == "pc":
        return _generate_pc(data, device_name, identity_only)
    return _generate_embedded(data, device_name, identity_only)
