from __future__ import annotations
from utils import trigger_config_expression, VALUE_TYPE_ENUM


def generate(data: dict) -> str:
    device_name = data["device"]
    guard = f"OPX_{device_name.upper()}_REGISTER_ALL_H"

    settings = data.get("settings", [])
    telemetry = data.get("telemetry", [])

    # ── settings registration body ────────────────────────────────────────────
    if settings:
        settings_body = "\n".join(
            f"    device.registerSetting("
            f"SettingID::{device_name}Setting::{s['name']}, "
            f"{VALUE_TYPE_ENUM[s['type']]});"
            for s in settings
        )
    else:
        settings_body = f"    // No settings defined for {device_name}"

    # ── telemetry registration body ───────────────────────────────────────────
    if telemetry:
        telemetry_body = "\n".join(
            f"    device.registerTelemetry("
            f"TelemetrySource::{device_name}TelemetrySource::{src['name']}, "
            f"{trigger_config_expression(src)});"
            for src in telemetry
        )
    else:
        telemetry_body = f"    // No telemetry defined for {device_name}"

    return f"""\
//
// {device_name}RegisterAll.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#pragma once

#ifdef OPX_EMBEDDED

#include "opx/shared/core/platform.h"
#include "opx/embedded/core/OpxDevice.h"
#include "opx/shared/core/TriggerConfig.h"
#include "../../SettingIDs.h"
#include "../../TelemetrySourceIDs.h"

inline void register{device_name}Settings(OpxDevice& device) {{
{settings_body}
}}

inline void register{device_name}Telemetry(OpxDevice& device) {{
{telemetry_body}
}}

#endif // OPX_EMBEDDED
"""
