from __future__ import annotations


def generate(data: dict) -> str:
    device_name = data["device"]

    return f"""\
//
// {device_name}Register.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#pragma once

#ifdef OPX_EMBEDDED

#include "opx/shared/core/platform.h"
#include "opx/embedded/core/OpxDevice.h"
#include "../../../shared/devices/{device_name}/{device_name}Controller.h"
#include "{device_name}RegisterAll.h"

// Single call to fully register this device with OpxDevice.
// Sets typeShift, registers all settings and telemetry sources.
inline void register{device_name}(OpxDevice& device) {{
    device.setTypeShift({device_name}Controller::TYPE_ID);
    register{device_name}Settings(device);
    register{device_name}Telemetry(device);
}}

#endif // OPX_EMBEDDED
"""
