from __future__ import annotations
from utils import shifted_id, to_hex


def generate(all_data: list[dict]) -> str:
    lines: list[str] = []

    lines.append("""\
//
// SettingIDs.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#pragma once

#include "opx/shared/core/platform.h"

namespace SettingID {
""")

    for data in all_data:
        if not data.get("settings"):
            continue

        device_name = data["device"]
        type_shift = data["typeShift"]

        lines.append(f"namespace {device_name}Setting {{\n")
        for setting in data["settings"]:
            name = setting["name"]
            sid = shifted_id(type_shift, setting["id"])
            if setting.get("description"):
                lines.append(f"    // {setting['description']}")
            lines.append(f"    constexpr uint16_t {name} = {to_hex(sid)};\n")
        lines.append(f"}} // namespace {device_name}Setting\n")

    lines.append("} // namespace SettingID\n")

    return "\n".join(lines)
