from __future__ import annotations
from utils import shifted_id, to_hex


def generate(all_data: list[dict]) -> str:
    lines: list[str] = []

    lines.append("""\
//
// TelemetrySourceIDs.h
// AUTO-GENERATED BY OmniPlexus CommandGenerator - DO NOT EDIT
//

#pragma once

#include "opx/shared/core/platform.h"

namespace TelemetrySource {
""")

    for data in all_data:
        if not data.get("telemetry"):
            continue

        device_name = data["device"]
        type_shift = data["typeShift"]

        lines.append(f"namespace {device_name}TelemetrySource {{\n")
        for source in data["telemetry"]:
            name = source["name"]
            sid = shifted_id(type_shift, source["id"])
            if source.get("description"):
                lines.append(f"    // {source['description']}")
            lines.append(f"    constexpr uint16_t {name} = {to_hex(sid)};\n")
        lines.append(f"}} // namespace {device_name}TelemetrySource\n")

    lines.append("} // namespace TelemetrySource\n")

    return "\n".join(lines)
