#ifndef COMMANDGENERATOR_GENERATOR_H
#define COMMANDGENERATOR_GENERATOR_H

#include <cstdint>
#include <string>
#include <iostream>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include "lib/nlohmann/json.hpp"

using json = nlohmann::json;

class Generator {
private:

    // Write a string to a file, throws on failure
    static void writeFile(const std::string& path, const std::string& content) {
        std::ofstream file(path);
        if (!file.is_open()) {
            throw std::runtime_error("Could not open file for writing: " + path);
        }
        file << content;
        file.close();
    }

    // Format uint16_t as "0x0001"
    static std::string toHex(const uint16_t value) {
        std::ostringstream oss;
        oss << "0x" << std::uppercase << std::hex
            << std::setw(4) << std::setfill('0') << value;
        return oss.str();
    }

    // Map a JSON type string to the C++ default initializer for unpack
    static std::string defaultForType(const std::string& type) {
        if (type == "FLOAT")  return "0.0f";
        if (type == "INT8")   return "int8_t(0)";
        if (type == "UINT8")  return "uint8_t(0)";
        if (type == "INT16")  return "int16_t(0)";
        if (type == "UINT16") return "uint16_t(0)";
        if (type == "INT32")  return "int32_t(0)";
        if (type == "UINT32") return "uint32_t(0)";
        if (type == "STRING") return "\"\"";
        return "0";
    }

    // Map a JSON type string to sizeof expression
    // string uses getDataSize()
    static std::string sizeofForType(const std::string& type) {
        if (type == "FLOAT")  return "sizeof(float)";
        if (type == "INT8")   return "sizeof(int8_t)";
        if (type == "UINT8")  return "sizeof(uint8_t)";
        if (type == "INT16")  return "sizeof(int16_t)";
        if (type == "UINT16") return "sizeof(uint16_t)";
        if (type == "INT32")  return "sizeof(int32_t)";
        if (type == "UINT32") return "sizeof(uint32_t)";
        return "0";
    }

    // Map a JSON type string to the ValueType enum name
    static std::string valueTypeEnum(const std::string& type) {
        return "ValueType::" + type;
    }

    // Compute the minimum expected payload size for a command (required params only)
    static size_t minPayloadSize(const json& cmd) {
        size_t size = 2; // commandType is always 2 bytes
        if (!cmd.contains("params")) return size;

        for (const auto& param : cmd["params"]) {
            if (!param["required"].get<bool>()) continue;

            const std::string type = param["type"].get<std::string>();
            if (type == "FLOAT")        size += 4;
            else if (type == "INT8")    size += 1;
            else if (type == "UINT8")   size += 1;
            else if (type == "INT16")   size += 2;
            else if (type == "UINT16")  size += 2;
            else if (type == "INT32")   size += 4;
            else if (type == "UINT32")  size += 4;
            else if (type == "STRING")  size += 1; // At minimum 1 byte (typeAndSize only for empty string)
        }
        return size;
    }

    // ─────────────────────────────────────────────────────────────────────
    // File Generators
    // ─────────────────────────────────────────────────────────────────────

    static std::string generateCommandTypesContent(const json& data) {
        std::ostringstream out;

        out << "//\n";
        out << "// CommandTypes.h\n";
        out << "// AUTO-GENERATED BY SmartDrive CommandGenerator - DO NOT EDIT\n";
        out << "// Source: commands.json\n";
        out << "//\n\n";
        out << "#ifndef SMARTDRIVE_COMMANDTYPES_H\n";
        out << "#define SMARTDRIVE_COMMANDTYPES_H\n\n";
        out << "#include <cstdint>\n\n";
        out << "namespace CommandType {\n\n";

        for (const auto& cmd : data["commands"]) {
            const std::string name = cmd["name"].get<std::string>();
            const uint16_t    id   = cmd["id"].get<uint16_t>();

            // Include description as comment if available
            if (cmd.contains("description") && !cmd["description"].get<std::string>().empty()) {
                out << "    // " << cmd["description"].get<std::string>() << "\n";
            }
            out << "    constexpr uint16_t " << name
                << " = " << toHex(id) << ";\n\n";
        }

        out << "} // namespace CommandType\n\n";
        out << "#endif // SMARTDRIVE_COMMANDTYPES_H\n";

        return out.str();
    }

    static std::string generateCommandPackerContent(const json& data) {
        std::ostringstream out;

        out << "//\n";
        out << "// CommandPacker.h\n";
        out << "// AUTO-GENERATED BY SmartDrive CommandGenerator - DO NOT EDIT\n";
        out << "// Source: commands.json\n";
        out << "//\n\n";
        out << "#ifndef SMARTDRIVE_COMMANDPACKER_H\n";
        out << "#define SMARTDRIVE_COMMANDPACKER_H\n\n";
        out << "#include <cstdint>\n";
        out << "#include <cstring>\n";
        out << "#include \"CommandTypes.h\"\n";
        out << "#include \"../types/ProtocolTypes.h\"\n\n";
        out << "class CommandPacker {\n";
        out << "public:\n\n";

        // ── pack() ──────────────────────────────────────────────────────
        out << "    // Serialize a Command into buffer\n";
        out << "    // Returns number of bytes written, 0 on failure\n";
        out << "    static size_t pack(const Command& cmd, uint8_t* buffer) {\n";
        out << "        size_t offset = 0;\n\n";
        out << "        // Write commandType (little-endian)\n";
        out << "        buffer[offset++] = cmd.commandType & 0xFF;\n";
        out << "        buffer[offset++] = (cmd.commandType >> 8) & 0xFF;\n\n";
        out << "        switch(cmd.commandType) {\n\n";

        for (const auto& cmd : data["commands"]) {
            const std::string name = cmd["name"].get<std::string>();

            out << "            case CommandType::" << name << ": {\n";

            if (!cmd.contains("params") || cmd["params"].empty()) {
                out << "                // No parameters\n";
                out << "                return offset;\n";
            } else {
                int paramIdx = 0;
                for (const auto& param : cmd["params"]) {
                    // Phase 1: Only serialize required parameters
                    if (!param["required"].get<bool>()) {
                        paramIdx++;
                        continue;
                    }

                    const std::string paramName = param["name"].get<std::string>();
                    const std::string type      = param["type"].get<std::string>();

                    out << "                // params[" << paramIdx << "]: "
                        << paramName << " (" << type << ", required)\n";

                    if (type == "STRING") {
                        // STRING: use getDataSize() for variable length
                        out << "                {\n";
                        out << "                    const size_t strSize = cmd.params["
                            << paramIdx << "].getDataSize();\n";
                        out << "                    std::memcpy(&buffer[offset], cmd.params["
                            << paramIdx << "].getData(), strSize);\n";
                        out << "                    offset += strSize;\n";
                        out << "                }\n";
                    } else {
                        // Numeric: fixed size via sizeof
                        out << "                std::memcpy(&buffer[offset], cmd.params["
                            << paramIdx << "].getData(), " << sizeofForType(type) << ");\n";
                        out << "                offset += " << sizeofForType(type) << ";\n";
                    }

                    paramIdx++;
                }
                out << "                return offset;\n";
            }

            out << "            }\n\n";
        }

        out << "            default:\n";
        out << "                return 0; // Unknown command type\n";
        out << "        }\n";
        out << "    }\n\n";

        // ── unpack() ─────────────────────────────────────────────────────
        out << "    // Deserialize a Command from buffer\n";
        out << "    // Returns true on success\n";
        out << "    static bool unpack(const uint8_t* buffer, size_t bufferSize, Command& cmdOut) {\n";
        out << "        if (bufferSize < 2) return false;\n\n";
        out << "        size_t offset = 0;\n\n";
        out << "        // Read commandType (little-endian)\n";
        out << "        const uint16_t cmdType =\n";
        out << "            static_cast<uint16_t>(buffer[offset]) |\n";
        out << "            (static_cast<uint16_t>(buffer[offset + 1]) << 8);\n";
        out << "        offset += 2;\n";
        out << "        cmdOut.commandType = cmdType;\n\n";
        out << "        switch(cmdType) {\n\n";

        for (const auto& cmd : data["commands"]) {
            const std::string name    = cmd["name"].get<std::string>();
            const size_t      minSize = minPayloadSize(cmd);

            out << "            case CommandType::" << name << ": {\n";

            if (!cmd.contains("params") || cmd["params"].empty()) {
                out << "                // No parameters\n";
                out << "                return true;\n";
            } else {
                out << "                if (bufferSize < " << minSize << ") return false;\n\n";

                int paramIdx = 0;
                for (const auto& param : cmd["params"]) {
                    // Phase 1: Only deserialize required parameters
                    if (!param["required"].get<bool>()) {
                        paramIdx++;
                        continue;
                    }

                    const std::string paramName = param["name"].get<std::string>();
                    const std::string type      = param["type"].get<std::string>();
                    const std::string defVal    = defaultForType(type);

                    out << "                // params[" << paramIdx << "]: "
                        << paramName << " (" << type << ", required)\n";

                    if (type == "STRING") {
                        out << "                cmdOut.params[" << paramIdx
                            << "] = " << defVal << "; // Set type\n";
                        out << "                {\n";
                        out << "                    const size_t strSize = cmdOut.params["
                            << paramIdx << "].getDataSize();\n";
                        out << "                    if (bufferSize < offset + strSize) return false;\n";
                        out << "                    std::memcpy(cmdOut.params[" << paramIdx
                            << "].getDataMutable(), &buffer[offset], strSize);\n";
                        out << "                    offset += strSize;\n";
                        out << "                }\n";
                    } else {
                        out << "                cmdOut.params[" << paramIdx
                            << "] = " << defVal << "; // Set type\n";
                        out << "                std::memcpy(cmdOut.params[" << paramIdx
                            << "].getDataMutable(), &buffer[offset], "
                            << sizeofForType(type) << ");\n";
                        out << "                offset += " << sizeofForType(type) << ";\n";
                    }

                    out << "\n";
                    paramIdx++;
                }

                out << "                return true;\n";
            }

            out << "            }\n\n";
        }

        out << "            default:\n";
        out << "                return false; // Unknown command type\n";
        out << "        }\n";
        out << "    }\n\n";

        out << "}; // class CommandPacker\n\n";
        out << "#endif // SMARTDRIVE_COMMANDPACKER_H\n";

        return out.str();
    }

    static std::string generateCommandRegistryContent(const json& data) {
        std::ostringstream out;

        out << "//\n";
        out << "// CommandRegistry.cpp\n";
        out << "// AUTO-GENERATED BY SmartDrive CommandGenerator - DO NOT EDIT\n";
        out << "// Source: commands.json\n";
        out << "//\n\n";
        out << "#include \"../../include/smartdrive/registry/CommandRegistry.h\"\n";
        out << "#include \"../../include/smartdrive/generated/CommandTypes.h\"\n\n";
        out << "#ifndef EMBEDDED_BUILD\n\n";
        out << "void CommandRegistry::initialize() {\n\n";

        for (const auto& cmd : data["commands"]) {
            const std::string name = cmd["name"].get<std::string>();
            const std::string desc = cmd.contains("description")
                                     ? cmd["description"].get<std::string>()
                                     : "";

            out << "    // " << name << "\n";
            out << "    registerCommand({\n";
            out << "        CommandType::" << name << ",\n";
            out << "        \"" << name << "\",\n";
            out << "        \"" << desc << "\",\n";
            out << "        {\n";

            if (cmd.contains("params")) {
                for (const auto& param : cmd["params"]) {
                    const std::string paramName = param["name"].get<std::string>();
                    const std::string type      = param["type"].get<std::string>();
                    const bool        required  = param["required"].get<bool>();
                    const std::string paramDesc = param.contains("description")
                                                  ? param["description"].get<std::string>()
                                                  : "";
                    const size_t maxLength = (type == "STRING" && param.contains("max_length"))
                                             ? param["max_length"].get<size_t>()
                                             : 0;
                    const std::string defVal = param.contains("default")
                                               ? param["default"].get<std::string>()
                                               : "";

                    out << "            {\""  << paramName << "\", "
                        << valueTypeEnum(type) << ", "
                        << (required ? "true" : "false") << ", "
                        << "\"" << paramDesc << "\", "
                        << maxLength << ", "
                        << "\"" << defVal << "\"},\n";
                }
            }

            out << "        }\n";
            out << "    });\n\n";
        }

        out << "} // CommandRegistry::initialize()\n\n";
        out << "#endif // EMBEDDED_BUILD\n";

        return out.str();
    }

public:

    // Generate all three output files
    // headerOutputDir → where CommandTypes.h and CommandPacker.h are written
    // sourceOutputDir → where CommandRegistry.cpp is written
    static void generate(const json& data,
                         const std::string& headerOutputDir,
                         const std::string& sourceOutputDir) {

        // Normalize paths (ensure trailing slash)
        std::string headerDir = headerOutputDir;
        std::string sourceDir = sourceOutputDir;
        if (!headerDir.empty() && headerDir.back() != '/') headerDir += '/';
        if (!sourceDir.empty() && sourceDir.back() != '/') sourceDir += '/';

        // Generate CommandTypes.h
        const std::string commandTypesPath = headerDir + "CommandTypes.h";
        writeFile(commandTypesPath, generateCommandTypesContent(data));
        std::cout << "  ✓ Generated: " << commandTypesPath << "\n";

        // Generate CommandPacker.h
        const std::string commandPackerPath = headerDir + "CommandPacker.h";
        writeFile(commandPackerPath, generateCommandPackerContent(data));
        std::cout << "  ✓ Generated: " << commandPackerPath << "\n";

        // Generate CommandRegistry.cpp
        const std::string commandRegistryPath = sourceDir + "CommandRegistry.cpp";
        writeFile(commandRegistryPath, generateCommandRegistryContent(data));
        std::cout << "  ✓ Generated: " << commandRegistryPath << "\n";
    }
};

#endif // COMMANDGENERATOR_GENERATOR_H