//
// PcApp.cpp
// Generated by OmniPlexus SessionBootstrap — starting point,
// safe to hand-edit from here on.
//

#include "autogen/pc/devices/PcApp/PcAppRegister.h"
#include "opx/pc/core/OpxSession.h"
#include <chrono>
#include <thread>

OpxSession session;

int main() {
  registerPcApp(session);
  session.connectWiFi("192.168.0.111", 9000, 5, 2000, 0);

  // OpxSession runs its listen/processing threads internally once a
  // transport is added — nothing needs polling here. This block just
  // keeps main() alive; it's a starting-point guess, not grounded in
  // an existing PC main.cpp convention from this project, so replace
  // it with your actual application logic.
  while (true) {
    std::this_thread::sleep_for(std::chrono::seconds(1));
  }

  return 0;
}
